version: '2'

services:
  db:
    image: postgres:9.3
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker

  web:
    depends_on:
      - db
    image: drupal:7
    links:
      - db
    ports:
      - "80:80"

volumes:
  data: {}
